name: process_tenx_xenium
namespace: datasets/workflows

argument_groups:
  - name: Inputs
    arguments:
      - type: file
        name: --input
        required: true
        description: A 10x xenium directory
        multiple: true
      - type: string
        name: --replicate_id
        required: true
        description: The replicate identifier
        multiple: true
      - type: string
        name: --segmentation_id
        required: true
        description: The segmentation identifier
        multiple: true
  - name: Metadata
    arguments:
      - type: string
        name: --dataset_id
        description: "A unique identifier for the dataset"
        required: true
      - name: --dataset_name
        type: string
        description: Nicely formatted name.
        required: true
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
      - name: --dataset_reference
        type: string
        description: Bibtex reference of the paper in which the dataset was published.
        required: false
      - name: --dataset_summary
        type: string
        description: Short description of the dataset.
        required: true
      - name: --dataset_description
        type: string
        description: Long description of the dataset.
        required: true
      - name: --dataset_organism
        type: string
        description: The organism of the sample in the dataset.
        required: false
  - name: Outputs
    arguments:
    - name: "--output"
      __merge__: /src/api/file_common_spatialdata.yaml
      direction: output
      required: true

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

dependencies:
  - name: datasets/loaders/tenx_xenium

runners:
  - type: nextflow
