ROOT: C:/Users/Habib/Projects/HMGU/tx_project
RESULTS: results
py_env : pipeline

PREPROCESSING:
  batch1:
    segmentation:
      cellpose:
    segmentation_params:
      expand: [0, 10]
      binary: [False]
    assignment: 
      pciSeq:
        opts: [{'exclude_genes':['TCIM']}, {}]
    normalize:
      area:
        alpha: [0]
        max: [True]
      total:
    dataset: [test]


DATA_SCENARIOS:
  heart:
    image: heart/raw_data/nuclei_PCW4.5_1.tif
    sc_data: heart/raw_data/heart_sc.h5ad
    molecules: heart/raw_data/spots_PCW4.5_1.csv
  heart2:
    image: heart/raw_data/nuclei_PCW4.5_1_watershed.tif
    sc_data: heart/raw_data/heart_sc.h5ad
    molecules: heart/raw_data/spots_PCW4.5_1.csv
  test:
    image: test/raw_image.tif
    sc_data: test/sc_data.h5ad
    molecules: test/spots.csv
