#Folder where pipeline is contained (should end with 'txsim-pipeline')
#This might be obsolete given snakemake functionality
#ROOT: /home/icb/hrehman80//txsim-pipeline
ROOT: /mnt/c/Users/Habib/Projects/HMGU/tx_project/txsim-pipeline

#Folder where intermediate/final files will be stored
#RESULTS: /lustre/groups/ml01/projects/2022_txsim_louis.kuemmerle/results
RESULTS: /mnt/d/HMGU/DATA/results

#Folder where temporary files will be stored (optional)
#TEMP: /localscratch/hrehman80
TEMP: /mnt/d/HMGU/DATA/baysor/temp


PREPROCESSING:
  # batch1:
  #   dataset: [test]
  #   workflow: [cell-segmentation, normalize]
  #   cell-segmentation:
  #     baysor:
  #   normalize:
  #     area:
  batch2:
    dataset: [test]
    workflow: [segmentation, assignment, normalize, annotate]
    segmentation:
      cellpose:
        min_size: [0]
        # flow_threshold: [True]
    segmentation_params:
      expand: [0]
    assignment:
      # basic:
      pciSeq: #TODO opts might not be working
        opts: [{'max_iter': 1002}]
    normalize:
      area:
        use_max_area: [True]
    normalize_params:
      # prior_threshold: [0.501]
      # max_area: [4000, 20000]  
      # min_area: [100, 500, 750]
      min_counts: [2]
      # min_cell_percentage: 0.5
    annotate:
      pciSeqCT:
        threshold: [0.6]
    annotate_params:
      per_gene_correction : [False]
    



METRICS:
  # batch1:
  #   dataset: test
  #   metrics: all
  #   files: all
  

DATA_SCENARIOS:
  test:
    check_dataset: False
    root_folder: /mnt/d/HMGU/DATA/test 
    sc_data: sc_data.h5ad
    segmented_image: segmented_image.tif
    images: [raw_image.tif]
    molecules: [spots.csv]
  test_xenium:
    check_dataset: False
    root_folder: /mnt/d/HMGU/DATA/Xenium 
    sc_data: scdata.h5ad
    images: [test_replicates/image1.tif, test_replicates/image2.tif, test_replicates/image3.tif]
    molecules: [test_replicates/spots_rep1.csv, test_replicates/spots_rep2.csv, test_replicates/spots_rep3.csv]
  # hippocampus:
  #   root_folder: /mnt/d/HMGU/DATA/hippocampus 
  #   image: CA1DapiBoundaries_7-1_right.tif
  #   sc_data: scdata.h5ad
  #   molecules: spots_w_celltype_rightCA1_7-1.csv

# DATA_SCENARIOS:
#   test:
#     root_folder: /home/icb/hrehman80/test_data
#     image: raw_image.tif
#     sc_data: sc_data.h5ad
#     molecules: spots.csv
#   heart_PCW4.5:
#     root_folder: /lustre/groups/ml01/projects/2022_txsim_louis.kuemmerle/heart_data
#     image: nuclei_PCW4.5_1.tif
#     sc_data: heart_sc.h5ad
#     molecules: spots_PCW4.5_1.csv
