ROOT: /mnt/c/Users/Habib/Projects/HMGU/tx_project
RESULTS: results
py_env : pipeline

#TODO: Add list of method types here
#List the combos somewhere somehow
#Make parsed config generic enough that it can generate the combos

PREPROCESSING:
  batch1:
    dataset: [test]
    workflow: [segmentation, assignment, normalize]
    segmentation:
      cellpose:
    segmentation_params:
      expand: [0]
      binary: [False]
    assignment: 
      pciSeq:
    normalize:
      area:
        alpha: [0]
        max: [True]


DATA_SCENARIOS:
  heart:
    image: heart/raw_data/nuclei_PCW4.5_1.tif
    sc_data: heart/raw_data/heart_sc.h5ad
    molecules: heart/raw_data/spots_PCW4.5_1.csv
  heart2:
    image: heart/raw_data/nuclei_PCW4.5_1_watershed.tif
    sc_data: heart/raw_data/heart_sc.h5ad
    molecules: heart/raw_data/spots_PCW4.5_1.csv
  test:
    image: test/raw_image.tif
    sc_data: test/sc_data.h5ad
    molecules: test/spots.csv
