#Folder where pipeline is contained (should end with 'txsim-pipeline')
ROOT: /mnt/c/Users/Habib/Projects/HMGU/tx_project/txsim-pipeline
#Folder where intermediate/final files will be stored
RESULTS: /mnt/d/HMGU/DATA/results

#TODO: Add list of method types here
#List the combos somewhere somehow
#Make parsed config generic enough that it can generate the combos

PREPROCESSING:
  batch1:
    dataset: [test]
    workflow: [segmentation, assignment, normalize]
    segmentation:
      cellpose:
        min_size: [15]
    segmentation_params:
      expand: [10]
      binary: [False]
    assignment: 
      pciSeq:
    normalize:
      area:
        alpha: [0]
        max: [True]


DATA_SCENARIOS:
  heart:
    image: heart/raw_data/nuclei_PCW4.5_1.tif
    sc_data: heart/raw_data/heart_sc.h5ad
    molecules: heart/raw_data/spots_PCW4.5_1.csv
  heart2:
    image: heart/raw_data/nuclei_PCW4.5_1_watershed.tif
    sc_data: heart/raw_data/heart_sc.h5ad
    molecules: heart/raw_data/spots_PCW4.5_1.csv
  test:
    root_folder: /mnt/d/HMGU/DATA/test 
    image: raw_image.tif
    sc_data: sc_data.h5ad
    molecules: spots.csv
