#Folder where pipeline is contained (should end with 'txsim-pipeline')
ROOT: /mnt/c/Users/Habib/Projects/HMGU/tx_project/txsim-pipeline

#Folder where intermediate/final files will be stored
RESULTS: /mnt/d/HMGU/DATA/results

#Folder where temporary files will be stored (optional)
TEMP: /mnt/d/HMGU/DATA/baysor/temp

#TEMP: /localscratch/hrehman80
#ROOT: /home/icb/hrehman80//txsim-pipeline
#RESULTS: /lustre/groups/ml01/projects/2022_txsim_louis.kuemmerle/results

PREPROCESSING:
  # batch1:
  #   dataset: [test]
  #   workflow: [segmentation, assignment, normalize]
  #   segmentation:
  #     custom:
  #   segmentation_params:
  #     expand: [20]
  #   assignment: 
  #     pciSeq: 
  #       opts: [{}]
  #   normalize:
  #     area:
  #       alpha: [0]
  #       max: [True]
  batch2:
    dataset: [test]
    workflow: [cell_segmentation, normalize]
    segmentation:
      baysor:
    cell_segmentation:
      baysor:
    cell_segmentation_params:
      expand: [10]
      binary: [False]
    assignment: 
      basic:
    normalize:
      area:
        alpha: [0]
        max: [True]

DATA_SCENARIOS:
  test:
    root_folder: /mnt/d/HMGU/DATA/test 
    image: raw_image.tif
    sc_data: sc_data.h5ad
    molecules: spots.csv
    segmented_image: segmented_image.tif

# DATA_SCENARIOS:
#   test:
#     root_folder: /home/icb/hrehman80/test_data
#     image: raw_image.tif
#     sc_data: sc_data.h5ad
#     molecules: spots.csv
#   heart_PCW4.5:
#     root_folder: /lustre/groups/ml01/projects/2022_txsim_louis.kuemmerle/heart_data
#     image: nuclei_PCW4.5_1.tif
#     sc_data: heart_sc.h5ad
#     molecules: spots_PCW4.5_1.csv
