ROOT: C:/Users/Habib/Projects/HMGU/tx_project
RESULTS: results
py_env : pipeline

PREPROCESSING:
  batch1:
    segmentation: 
      watershed:
    segmentation_params:
      expand: [0]
      binary: [False]
    assignment: 
      pciSeq:
        opts: [{'exclude_genes':['TCIM']}]
    normalize: 
      total:
      area:
        type: [None]
    dataset: [heart]
  batch2:
    segmentation: 
      imagej:
      watershed:
    segmentation_params:
      expand: [0, 10]
      binary: [True]
    assignment: 
      pciSeq:
        opts: [{'exclude_genes':['TCIM']}]
    normalize: 
      total:
    dataset: [heart2]

DATA_SCENARIOS:
  heart:
    image: heart/raw_data/nuclei_PCW4.5_1.tif
    sc_data: heart/raw_data/heart_sc.h5ad
    molecules: heart/raw_data/spots_PCW4.5_1.csv
  heart2:
    image: heart/raw_data/nuclei_PCW4.5_1_watershed.tif
    sc_data: heart/raw_data/heart_sc.h5ad
    molecules: heart/raw_data/spots_PCW4.5_1.csv
