cluster: 
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --job-name=smk_{rule}
    --output=logs/{rule}/output_%j.txt
    --error=logs/{rule}/output_%j.txt
    --mem={resources.mem_mb}
    --nice=10000
    --mail-user=hrehman80@helmholtz-muenchen.de
    --time=12:00:00
default-resources:
  - partition=cpu_p
  - mem_mb=16000
use-conda: True
use-singularity: True
singularity-args:
  --bind /home/:/home/,/lustre/:/lustre/,/localscratch/:/localscratch/
jobs: 15
keep-going: True
restart-times: 2
