executor: cluster-generic
cluster-generic-submit-cmd:
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --qos={resources.qos}
    --job-name=smk_{rule}
    --output=logs/{rule}_output_%j.txt
    --error=logs/{rule}_output_%j.txt
    --mem={resources.mem_mb}
    --nice=10000
    --mail-user=hrehman80@helmholtz-muenchen.de
    --time=36:00:00
default-resources:
  - partition=cpu_p
  - qos=cpu_normal
  - mem_mb=16000
use-conda: True
use-singularity: True
#software-deployment-method: "conda apptainer"
singularity-args: "--bind /home/:/home/,/lustre/:/lustre/,/localscratch/:/localscratch/"
jobs: 40
keep-going: True
restart-times: 2