# __merge__: ../../api/comp_data_loader.yaml # TODO: loader for scrnaseq h5ad instead of spatialdata zarr 
name: download_allen_brain_cell_atlas
namespace: data_loaders

argument_groups:
  - name: Inputs
    arguments:
      - type: string
        name: --regions
        required: false
        description: A list of brain regions to download data for. If not provided, data for all regions will be downloaded.
        multiple: true
        default:
          - CTXsp
          - HPF
          - HY
          - Isocortex-1
          - Isocortex-2
          - Isocortex-3
          - Isocortex-4
          - MB
          - OLF
          - TH
  - name: Outputs
    arguments:
      - type: file
        name: --output
        required: true
        direction: output
        example: output.h5ad
        description: Path to the output h5ad file.

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: 
          - git+https://github.com/alleninstitute/abc_atlas_access
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, midcpu, midtime]
